Repository TeamSantas/front-santas, pull requests merged in 2022-11, with the labels that each got.

#2 [feature/SAN-23]: 프론트엔드 프로젝트 환경세팅
   .babelrc
  component/common/Seo.tsx
  component/layout/Footer.tsx
  component/layout/Header.tsx
  component/layout/Layout.tsx
  component/layout/Nav.tsx
  package-lock.json
  package.json
  pages/_app.js
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.js
  pages/api/hello.ts
  pages/index.js
  pages/index.tsx
  pages/mypage.tsx
  public/asset/image/favicon.ico
  public/favicon.ico
  public/vercel.svg
  styles/Home.module.css
  styles/globals.css
  tsconfig.json
Labels: 환경설정

#3 [Feature/san 54] 화면 캡쳐기능 생성
  .idea/front-santas.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  pages/index.tsx
  pages/mypage.tsx
  public/asset/image/santa.png
  styles/Home.module.css
Labels: 새로운기능

#6 Feature/SAN-52 : API 로직생성 및 반응형디자인 추가
  api/APIInstance.ts
  api/AuthService.ts
  api/FriendsService.ts
  api/MemberService.ts
  api/PostService.ts
  api/PresentService.ts
  api/SettingService.ts
  api/hooks/useGetAllPosts.ts
  component/Card.tsx
  component/TabView.tsx
  component/layout/Header.tsx
  component/layout/Layout.tsx
  package-lock.json
  package.json
  pages/api/hello.ts
  pages/index.tsx
  pages/mypage.tsx
  public/asset/image/Calendar.png
  public/asset/image/Calendar.svg
  public/asset/image/Logo.png
  public/asset/image/Logo.svg
  public/asset/image/days/day1.svg
  public/asset/image/face.svg
  styles/Home.module.css
  styles/globals.css
  styles/styledComponentModule.tsx
  util/type.ts
Labels: 추후확인필요, 리팩토링, 새로운기능

#7 Feature/SAN-92 : 선물(쪽지) 모달 구현
  component/Calendar.tsx
  component/Card.tsx
  component/CustomModal.tsx
  component/PresentCardList.tsx
  component/PresentModal.tsx
  component/TabView.tsx
  pages/_app.tsx
  pages/index.tsx
  public/asset/image/days/day1.svg
  public/asset/image/days/day10.svg
  public/asset/image/days/day11.svg
  public/asset/image/days/day12.svg
  public/asset/image/days/day13.svg
  public/asset/image/days/day14.svg
  public/asset/image/days/day15.svg
  public/asset/image/days/day16.svg
  public/asset/image/days/day17.svg
  public/asset/image/days/day18.svg
  public/asset/image/days/day19.svg
  public/asset/image/days/day2.svg
  public/asset/image/days/day20.svg
  public/asset/image/days/day21.svg
  public/asset/image/days/day22.svg
  public/asset/image/days/day23.svg
  public/asset/image/days/day24.svg
  public/asset/image/days/day25.svg
  public/asset/image/days/day3.svg
  public/asset/image/days/day4.svg
  public/asset/image/days/day5.svg
  public/asset/image/days/day6.svg
  public/asset/image/days/day7.svg
  public/asset/image/days/day8.svg
  public/asset/image/days/day9.svg
Labels: 리팩토링, 새로운기능

#9 [Feature/SAN-114]: BGM ON/OFF 기능 구현
  package-lock.json
  package.json
  pages/index.tsx
  public/asset/image/icons/muteSpeaker.png
  public/bgm.mp3
Labels: 새로운기능

#12 [Feature/SAN-109]: API 연결 및 설정페이지 작업
  api/APIInstance.ts
  api/FriendsService.ts
  api/MemberService.ts
  api/PostService.ts
  api/PresentService.ts
  api/hooks/useGetAllPosts.ts
  api/hooks/useGetFriend.ts
  api/hooks/useGetLoggedMember.ts
  api/hooks/useGetPresent.ts
  component/Calendar.tsx
  component/Card.tsx
  component/Sidebar.tsx
  component/layout/Header.tsx
  component/layout/Layout.tsx
  component/layout/Snows.tsx
  component/tab/TabView.tsx
  pages/edit.tsx
  pages/index.tsx
  pages/mypage.tsx
  styles/styledComponentModule.tsx
  util/type.ts
Labels: 리팩토링, 새로운기능

#10 [Feature/SAN-129] 캘린더 공유하기 Custom Modal 구현
  component/CustomModal.tsx
  component/share/Share.tsx
  package-lock.json
  pages/index.tsx
  public/asset/image/shareModalImg.svg
  styles/styledComponentModule.tsx
Labels: 리팩토링, 새로운기능

#15 [Feature/SAN-98] 쪽지 에디터 기능 구현
  component/Calendar.tsx
  component/Card.tsx
  component/CustomModal.tsx
  component/PresentCardList.tsx
  component/PresentModal.tsx
  component/Sidebar.tsx
  component/TabViewSY.tsx
  component/sendPresents/SendPresents.tsx
  component/sendPresents/TextArea.tsx
  component/share/Share.tsx
  component/tab/TabView.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/edit.tsx
  pages/index.tsx
  pages/mypage.tsx
  public/assets/image/XCircle.svg
  public/assets/image/greenXCircle.svg
  public/assets/image/message-background.svg
  styles/Home.module.css
  styles/globals.css
  styles/styledComponentModule.tsx
Labels: 리팩토링, 새로운기능
